project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
<<<<<<< HEAD
  title: "Fertility Rate"
  author:
    - Jingjing Dong (4125)
    - Emily Lu (2775)
  repo-url: https://github.com/emilylu2024/fertilityrate
=======
  title: "Fertility Rate Analyzation"
  author:
    - AUTHOR1 (UNI1)
    - Jingjing Dong (jd4125)
  repo-url: https://github.com/YOUR_GITHUB_ACCOUNT/REPO_NAME
>>>>>>> 9cf94d093aedbd996f55a99aa5ff05e613fb67ac
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


