# Conclusion

Based on our exploration, we found that fertility rates decline when life expectancy and the percentage of educational attainment increase. On the other hand, fertility and marriage rates have a positive correlation as they both demonstrate a declining trend across the globe. To our surprise, changes in divorce rates and GDP growth seem to be independent of the changes in fertility rates. In our further investigation of these two variables, we find that divorce rates are positively correlated with the marriage rate, while GDP growth is independent of the changes in marriage rates. This finding indicates that societal factors are probably more influential to changes in marriage rates than economic factors. Due to the lack of data for low-income countries and earlier periods in educational attainment, our analysis is limited to the countries that have middle or high incomes and time after 2014, which restricts the scope of our findings and might contribute to the differences between correlation matrix result and the findings shown by our graph. In the future, we could focus more on the direction of educational attainment to improve the strength of the conclusion by including a broader range of data in our analysis. In summary, the global decline in the fertility rate is associated with the improvement in healthcare and education and the decline in the marriage rate.

