---
title: "graphs_e"
author: "Emily Lu"
date: '2024-12-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
## install.packages("sf")
library(sf)
library(ggplot2)
library(readr)
library(tidyverse)
library(dplyr)
library(rmapshaper)
library(RColorBrewer)
library(cowplot)
```


## Global Fertility Trend
```{r}
fertility_rate<- read_csv("/Users/emilyl/Desktop/fertilityrate/fertility_long.csv")
marriage_rate <- read_csv("/Users/emilyl/Desktop/fertilityrate/marriage-rate-per-1000-inhabitants.csv")
```


```{r}
shapefile_path <-"/Users/emilyl/Desktop/fertilityrate/geoBoundariesCGAZ_ADM0/geoBoundariesCGAZ_ADM0.shp"
regions <- st_read(shapefile_path)
## head(regions)
simplified_shapefile <- ms_simplify(regions)

clean <- na.omit(fertility_rate)
min <- min(clean$fertility_rate) 
max <- max(clean$fertility_rate)
```


```{r}
custom_palette <- colorRampPalette(c("red", "white", "blue"))
my_color_scale <- scale_fill_gradientn(
    colors = custom_palette(100),
    na.value = "black",
    name = "Fertility Rate",
    limits = c(min, max)
  )
```


```{r}
## All Data

rate_1960 <- fertility_rate[fertility_rate$Year == 1960,]
map_1960 <- simplified_shapefile |>
  left_join(rate_1960, by = c("shapeGroup" = "Code"))

rate_1970 <- fertility_rate[fertility_rate$Year == 1970,]
map_1970 <- simplified_shapefile |>
  left_join(rate_1970, by = c("shapeGroup" = "Code"))

rate_1980 <- fertility_rate[fertility_rate$Year == 1980,]
map_1980 <- simplified_shapefile |>
  left_join(rate_1980, by = c("shapeGroup" = "Code"))

rate_1990 <- fertility_rate[fertility_rate$Year == 1990,]
map_1990 <- simplified_shapefile |>
  left_join(rate_1990, by = c("shapeGroup" = "Code"))

rate_2000 <- fertility_rate[fertility_rate$Year == 2000,]
map_2000 <- simplified_shapefile |>
  left_join(rate_2000, by = c("shapeGroup" = "Code"))

rate_2010 <- fertility_rate[fertility_rate$Year == 2010,]
map_2010 <- simplified_shapefile |>
  left_join(rate_2010, by = c("shapeGroup" = "Code"))

rate_2020 <- fertility_rate[fertility_rate$Year == 2020,]
map_2020 <- simplified_shapefile |>
  left_join(rate_2020, by = c("shapeGroup" = "Code"))
```


```{r}
ggplot(map_1960) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "Global Fertility Rate",
       subtitle = "Year 1960") +
  theme(panel.grid = element_blank())
```



```{r}
ggplot(map_1970) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "Global Fertility Rate",
       subtitle = "Year 1970") +
  theme(panel.grid = element_blank())
```




```{r}
ggplot(map_1980) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "Global Fertility Rate",
       subtitle = "Year 1980") +
  theme(panel.grid = element_blank())
```


```{r}
ggplot(map_1990) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "Global Fertility Rate",
       subtitle = "Year 1990") +
  theme(panel.grid = element_blank())
```

```{r}
ggplot(map_2000) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "Global Fertility Rate",
       subtitle = "Year 2000") +
  theme(panel.grid = element_blank())
```


```{r}
ggplot(map_2010) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "Global Fertility Rate",
       subtitle = "Year 2010") +
  theme(panel.grid = element_blank())
```


```{r}
ggplot(map_2020) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "Global Fertility Rate",
       subtitle = "Year 2020") +
  theme(panel.grid = element_blank())
```


```{r}
p1 <- ggplot(map_1960) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "1960") +
  theme(panel.grid = element_blank(),
        legend.position = "none")

p2 <- ggplot(map_1970) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "1970") +
  theme(panel.grid = element_blank(),
        legend.position = "none")

p3 <- ggplot(map_1980) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "1980") +
  theme(panel.grid = element_blank(),
        legend.position = "none")

p4 <- ggplot(map_1990) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "1990") +
  theme(panel.grid = element_blank(),
        legend.position = "none")

p5 <- ggplot(map_2000) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "2000") +
  theme(panel.grid = element_blank(),
        legend.position = "none")

p6 <- ggplot(map_2010) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "2010") +
  theme(panel.grid = element_blank(),
        legend.position = "none")

p7 <- ggplot(map_2020) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "2020") +
  theme(panel.grid = element_blank(),
        legend.position = "none")

legend <- get_legend(
 ggplot(map_1970) +
  geom_sf(aes(fill = fertility_rate)) +
  my_color_scale +
  labs(title = "1970") +
  theme(panel.grid = element_blank(),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.key.width = unit(2, "cm"))
)
```


```{r}
combined <- plot_grid(p2, p3, p4, 
                      p5, p6, p7,
                      NULL, legend, 
                      ncol = 3,
                      rel_heights = c(1, 1, 1, 
                                     1, 1, 1, 
                                     0.1, 0.1,0.1))
print(combined)
```

```{r}
title <- ggdraw() +
  draw_label(
    "Global Fertility Rate Trend",
    fontface = 'bold')


plot_grid(title, combined, ncol = 1, rel_heights = c(0.1, 1))
```

## Educational Attainment
```{r}
education <- read_csv("/Users/emilyl/Desktop/fertilityrate/education_long.csv")
```

```{r}
code <- unique(marriage_rate$Code)

education_country <-  education |>
  filter(Code %in% code)

fertility_country <-  fertility_rate |>
  filter(Code %in% code)
```

```{r}
education_clean <- na.omit(education_country)
education_clean <- education_clean |>
  filter(Year %in% c(2014:2022))
```

```{r}
edu_fertility <- left_join(education_clean, fertility_country, 
                           by = c("Code", "Year", "Country"))

row <- which(edu_fertility$education_level == "Doctoral or equivalent")
edu_fertility <- edu_fertility[-row,]
edu_fertility$education_level <- as.factor(edu_fertility$education_level)

## Removed Peru because of the lack of data
row <- which(edu_fertility$Country == "Peru")
edu_fertility <- edu_fertility[-row,]
```



```{r, fig.height=3, fig.width= 5}
ggplot(edu_fertility, aes(x = Year, y = Country, 
                          fill = educational_attainment)) +
  geom_tile() +
  facet_wrap(~education_level) + 
  scale_fill_gradient(low = "white", high = "blue") +
   scale_x_continuous(breaks = seq(2014, 2022, by = 1)) +
  labs(
    title = "Heatmap of Educational Attainment",
    x = "Year",
    y = "Country",
    fill = "Percentage (%)"
  )  + 
  theme(panel.grid.minor = element_blank() )
```

```{r}
data_combined <- edu_fertility %>%
  group_by(Country, Year) %>%
  summarize(
    education_level = "Bachelor's and Master's", 
    percentage = sum(educational_attainment)
  )

data_combined <- left_join(data_combined, fertility_country, 
                           by = c("Year", "Country"))

scaled_data <- data_combined


scaled_data$fertility_rate <- (scaled_data$fertility_rate - min(scaled_data$fertility_rate)) / (max(scaled_data$fertility_rate) - min(scaled_data$fertility_rate))

scaled_data$percentage <- (scaled_data$percentage - min(scaled_data$percentage)) / (max(scaled_data$percentage) - min(scaled_data$percentage))
 
```


```{r, fig.height=3, fig.width= 5}
ggplot(scaled_data, aes(x = Year)) +
  # Bar plot for educational attainment percentages
  geom_bar(
    aes(y = percentage, fill = "Bachelor's Degree or Higher"),
    stat = "identity") +
  # Line plot for fertility rate
  geom_line(
    aes(y = fertility_rate, group = Country, color = "Fertility Rate")) + 
  scale_x_continuous(
    breaks = seq(2014, 2022, by = 2)) + 
  scale_y_continuous(
    breaks = c(0,0.5,1),  
  ) +
  scale_fill_manual(
    name = "Bar", 
    values = c("Bachelor's Degree or Higher" = "lightblue")
  ) +
  scale_color_manual(
    name = "Line",
    values = c("Fertility Rate" = "black")
  ) +
  facet_wrap(~Country) +
  labs(
    title = "Educational Attainment and Fertility Rate by Country",
    x = "Year", y = "Scaled Educational Attainment and Fertility Rate (0-1)"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right",
        panel.grid.minor = element_blank())
```


## Life Expectancy
```{r}
life_expectancy <- read_csv("/Users/emilyl/Desktop/fertilityrate/life_long.csv")
row <- which(life_expectancy$Gender == "Both")
life_both <- life_expectancy[row,]

life_fertility <- fertility_country |>
  left_join(life_both, by = c("Country", "Year", "Code"))
```


```{r}
scaled_life <- life_fertility

scaled_life$fertility_rate <- (scaled_life$fertility_rate - min(scaled_life$fertility_rate)) / (max(scaled_life$fertility_rate) - min(scaled_life$fertility_rate))

scaled_life$life_expectancy <- (scaled_life$life_expectancy - min(scaled_life$life_expectancy)) / (max(scaled_life$life_expectancy) - min(scaled_life$life_expectancy))
```

```{r}
scaled_life_10 <- scaled_life |>
  filter(Year %in% seq(from = 1960, to = 2020, by = 10))
```

```{r, fig.height=3.5, fig.width= 5}
ggplot(scaled_life_10, aes(y = Country)) +
  geom_point(aes(x = fertility_rate, color = "Fertility Rate")) +  # Fertility Rate points
  geom_point(aes(x = life_expectancy, color = "Life Expectancy")) +  # Life Expectancy points
  facet_wrap(~Year, ncol = 3) + 
  scale_color_manual(
    name = "Metrics",
    values = c("Fertility Rate" = "blue", "Life Expectancy" = "red")
  ) +
  labs(
    title = "Fertility Rate and Life Expectancy by Country and Year",
    x = "Scaled Value (0-1)",
    y = "Country",
    color = "Metric"
  ) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 8),
    legend.position = "bottom"
  )
```


```{r, fig.height=3.5, fig.width= 5}
ggplot(scaled_life_10, aes(x = Country)) +
  geom_point(aes(y = fertility_rate, color = "Fertility Rate")) +  # Fertility Rate points
  geom_point(aes(y = life_expectancy, color = "Life Expectancy")) +  # Life Expectancy points
  facet_wrap(~Year, ncol = 3) + 
  scale_color_manual(
    name = "Metrics",
    values = c("Fertility Rate" = "blue", "Life Expectancy" = "red")
  ) +
  labs(
    title = "Fertility Rate and Life Expectancy by Country and Year",
    x = "Value",
    y = "Scaled Value (0-1)",
    color = "Metric"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
    legend.position = "bottom"
  )
```

## Life Expectancy
```{r}
gdp <- read_csv("/Users/emilyl/Desktop/fertilityrate/gdp_long.csv")
summary(fertility_rate)
```

```{r}
gdp_clean <- na.omit(gdp)

gdp_fertility <- gdp_clean |>
  left_join(fertility_rate, by = c("Country", "Code", "Year"))

gdp_fertility <- na.omit(gdp_fertility)

gdp_fertility <- gdp_fertility |>
  group_by(Year) |>        
  summarize(mean_fertility = mean(fertility_rate),
            mean_gdp = mean(gdp_growth)) 

scaled_gdp <- gdp_fertility
scaled_gdp$mean_fertility <- (scaled_gdp$mean_fertility - min(scaled_gdp$mean_fertility)) / (max(scaled_gdp$mean_fertility) - min(scaled_gdp$mean_fertility))

scaled_gdp$mean_gdp <- (scaled_gdp$mean_gdp - min(scaled_gdp$mean_gdp)) / (max(scaled_gdp$mean_gdp) - min(scaled_gdp$mean_gdp))
```


```{r}
ggplot(scaled_gdp, aes(x = Year)) +
  geom_line(aes(y = mean_fertility, color = "Fertility Rate")) +
  geom_line(aes(y = mean_gdp, color = "GDP Growth")) +
  scale_color_manual(values = c("Fertility Rate" = "blue", "GDP Growth" = "red")) +
  labs(
    title = "Global Trends in Fertility Rate and GDP Growth Over Time",
    x = "Year",
    y = "Scaled Values (0-1)",
    color = "Variables of Interest"
  ) +
  theme_minimal()
```

## Life expectancy and Marriage Rate

```{r}
colnames(marriage_rate)[1] <- "Country"
colnames(marriage_rate)[4] <- "marriage_rate"

life_marriage <- marriage_rate |>
  left_join(life_both, by = c("Country", "Code", "Year"))

life_marriage_scaled <- life_marriage

life_marriage_scaled <- na.omit(life_marriage_scaled)

life_marriage_scaled$marriage_rate <- (life_marriage_scaled$marriage_rate - min(life_marriage_scaled$marriage_rate)) / (max(life_marriage_scaled$marriage_rate) - min(life_marriage_scaled$marriage_rate))

life_marriage_scaled$life_expectancy <- (life_marriage_scaled$life_expectancy - min(life_marriage_scaled$life_expectancy)) / (max(life_marriage_scaled$life_expectancy) - min(life_marriage_scaled$life_expectancy))
```


```{r,fig.height=3, fig.width= 5}
ggplot(life_marriage_scaled, aes(x = Year)) +
  geom_line(aes(y = marriage_rate, color = "Marriage Rate")) +  # Fertility Rate points
  geom_line(aes(y = life_expectancy, color = "Life Expectancy")) +
  facet_wrap(~Country) +
  scale_color_manual(
    name = "Metrics",
    values = c("Marriage Rate" = "blue", "Life Expectancy" = "red")
  ) +
  labs(
    title = "Marriage Rate and Life Expectancy by Country",
    x = "Year",
    y = "Scaled Value (0-1)"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.spacing = unit(1, "lines"))
```




